#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World!'.
#

apt-get update
apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" > /var/www/html/index.html
sudo service nginx restart
