#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Holberton School'.
#
# Also, the script, configure a directive of the Nginx server
# to redirect to another page with 301 HTTP Code
#

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart

