#!/usr/bin/env bash
# 
# Configure Nginx so that its HTTP response contains
# a custom header
#

# Update packages
sudo apt update

# Add HAProxy PPA
sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
sudo apt update

# Install HAProxy
sudo apt-get install haproxy=2.7.\*

hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer
fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server 66510-web-01 100.26.241.192:80 check"
bserver2="server 66510-web-02 35.168.8.232:80 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

# Restart HAProxy
sudo service haproxy restart
